name: release-github

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

env:
  CONAN_USER: ${{ secrets.ARTIFACTORY_CONAN_USERNAME }}
  CONAN_TOKEN: ${{ secrets.ARTIFACTORY_CONAN_ACCESS_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: "westonrobot/ubuntu:jammy-ci-latest"
    permissions:
      contents: write
    steps:
      - name: Create release
        uses: westonrobot-dev/release-action@v1.13.0
        with:
          generateReleaseNotes: true